name: quixote_app
description: "Um app do balacobaco"
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  cupertino_icons: ^1.0.2
  google_fonts: ^6.0.0
  flutter_native_splash: ^2.3.7
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
    




flutter:


  uses-material-design: true


  assets:
    - assets/images/


  






